### ISSUE TITLE
Контакт с разработчиком.

### ISSUE THREAD

**Issue by 4D4N-P** [olkhovichs/groceryShop_TelegramBot#1]
Доброго времени суток уважаемый olkhovichs. Сегодня мне пришла идея в голову создать такого же бота и у меня получилось это благодаря вашим "Исходникам". Я бы хотел помочь развить ваш проект, могу я получить ваш контакт?

**Comment by olkhovichs** [comment]
> Доброго времени суток уважаемый olkhovichs. Сегодня мне пришла идея в голову создать такого же бота и у меня получилось это благодаря вашим "Исходникам". Я бы хотел помочь развить ваш проект, могу я получить ваш контакт?

Здравствуйте, @4D4N-P, все контакты есть в моем профиле.
