### ISSUE TITLE
To remove the history of communication

### ISSUE THREAD

**Issue by olkhovichs** [olkhovichs/groceryShop_TelegramBot#2]
I need to add the deletion of all correspondence with the bot when clicking on inline button 'exit'
Мне нужно добавить удаление всей переписки с ботом при нажатии на встроенную кнопку "exit"
Here/Здесь: 
main.py
```
# exit
dp.callback_query_handler(lambda call: call.data == 'exit')
async def exit_bot(callback_query: types.CallbackQuery):
```

**Comment by 4D4N-P** [comment]
Привет @olkhovichs. Добавь обычное удаление сообщений после нажатия на любую клавишу как это сделал я. 
Просто добавь:
    await bot.delete_message(call.from_user.id, call.message.message_id)
    await bot.answer_callback_query(call.id)
После обработки каждого callback_query_handler
